### ISSUE TITLE
wrong assumption about browser or server

### ISSUE THREAD

**Issue by muradm** [kamilkisiela/apollo-angular-ssr#2]
If there is no key in `transferState` while in browser will attempt to follow `onServer` path which is wrong. Better to relay on `isPlatformBrowser()`?

https://github.com/kamilkisiela/apollo-angular-ssr/blob/b30535ee24a5caf0c174bc5ad11fdd3209ccdc5b/src/app/graphql.module.ts#L39

**Comment by kamilkisiela** [comment]
`isBrowser` always will be `true` in browser because we serialize data on server and of course, you can use isPlatformBrowser() or anything you want to.
